### PR TITLE
Eric eggleston

### PR DESCRIPTION
**Pull request by Pkmartus**

### CODE REVIEW

**Review by bpetroski — CHANGES_REQUESTED** [review]
He really needs to pull from main onto his branch. This pull request includes every change we've made from multiple branches and it's kinda sketching me out. If it makes it easier I would just create a new branch and start fresh. @Pkmartus

**Comment by Pkmartus** [comment]
KK I'll take some screenshots and see if I can explain the correct way to pull @bpetroski

**Comment by bpetroski** [comment]
> KK I'll take some screenshots and see if I can explain the correct way to pull @bpetroski

thanks

**Comment by Pkmartus** [comment]
@bpetroski I might just use the HanChoi2 branch and copy and paste for now till we get it sorted out

**Comment by bpetroski** [comment]
that should be fine, really there is no downside to just making a new branch when you run into issues from what I can see.

**Pull request closed without merging**
